### ISSUE TITLE
Creeps do a 360 Turn when not required. 

### ISSUE THREAD

**Issue by Kegley** [Helam24/Screeps-Observer-Public#1]
When Creeps are moving toward target, theres a behavior that some of them turn 360 and then move. Not really a blocker to playing, more just a view issue. 

![44A56E72-6227-4883-87C1-FC6E4D3EACE0](https://user-images.githubusercontent.com/2308319/80639445-05e24680-8a30-11ea-8a48-143f892a8c1f.GIF)

**Comment by Helam24** [comment]
This should be improved with the latest version from a few days ago (with the nukes list). It still isn’t perfect as sometimes they turn the long way around instead of the shorter turn in the correct direction but they shouldn’t be doing 360s anymore.

**Comment by Helam24** [comment]
I believe this is resolved now
