### ISSUE TITLE
unsubscribe roomMap2 after one tick

### ISSUE THREAD

**Issue by bastianh** [Helam24/Screeps-Observer-Public#10]
As far as I understand the roomMap2 endpoint fetches structures for the mapview.

the official client subscribes to all visible rooms and unsubscribes after one tick after it got the date, because otherwise  it sends the same data every tick.

I think that's a good idea to save bandwith with client and server.

**Comment by bastianh** [comment]
sorry.. my fault.. saw that creeps are also in there..

**Comment by Helam24** [comment]
@bastianh no problem, I appreciate the intention 😄
