### ISSUE TITLE
new build roads are not connected

### ISSUE THREAD

**Issue by bastianh** [Helam24/Screeps-Observer-Public#7]
If you watch a room and roads are constructed they are not connected until you reload the room

![IMG_7E80CC444FC7-1](https://user-images.githubusercontent.com/17590/103283907-18a38580-49da-11eb-82ef-474ff7854811.jpeg)

**Comment by Helam24** [comment]
@bastianh this should be fixed in 1.7.9 (3) that is now in TestFlight. Thank you!
